[package]
name = "tokio_actors"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1", features = ["full"]}
futures = "*"
tokio-stream = { version = "0.1", features = ["sync"] }
async-trait = "0.1"
